/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


package it.csi.aura.auraws.services.central.anagrafesanitaria;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-14T11:56:42.613+02:00
 * Generated source version: 3.3.2
 *
 */
public final class AnagrafeSanitariaSoap_AnagrafeSanitariaSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", "AnagrafeSanitaria");

    private AnagrafeSanitariaSoap_AnagrafeSanitariaSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AnagrafeSanitaria.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AnagrafeSanitaria ss = new AnagrafeSanitaria(wsdlURL, SERVICE_NAME);
        AnagrafeSanitariaSoap port = ss.getAnagrafeSanitariaSoap();

        {
        System.out.println("Invoking getProfiloSanitario...");
        java.lang.String _getProfiloSanitario_aurAid = "";
        it.csi.aura.auraws.services.central.anagrafesanitaria.SoggettoAuraMsg _getProfiloSanitario__return = port.getProfiloSanitario(_getProfiloSanitario_aurAid);
        System.out.println("getProfiloSanitario.result=" + _getProfiloSanitario__return);


        }

        System.exit(0);
    }

}
