/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.aura.auraws.services.central.anagrafesanitaria;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-14T11:56:42.734+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", name = "AnagrafeSanitariaSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AnagrafeSanitariaSoap {

    @WebMethod(operationName = "GetProfiloSanitario", action = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it/AURA.WS.AnagrafeSanitaria.GetProfiloSanitario")
    @RequestWrapper(localName = "GetProfiloSanitario", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.anagrafesanitaria.GetProfiloSanitario")
    @ResponseWrapper(localName = "GetProfiloSanitarioResponse", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.anagrafesanitaria.GetProfiloSanitarioResponse")
    @WebResult(name = "GetProfiloSanitarioResult", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it")
    public it.csi.aura.auraws.services.central.anagrafesanitaria.SoggettoAuraMsg getProfiloSanitario(

        @WebParam(name = "AURAid", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it")
        java.lang.String aurAid
    );
}
