/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.aura.auraws.services.central.anagrafesanitaria;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-14T11:56:42.746+02:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "AnagrafeSanitaria",
                  wsdlLocation = "https://tst-portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeSanitaria.cls?wsdl",
                  targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it")
public class AnagrafeSanitaria extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", "AnagrafeSanitaria");
    public final static QName AnagrafeSanitariaSoap = new QName("http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", "AnagrafeSanitariaSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://tst-portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeSanitaria.cls?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AnagrafeSanitaria.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://tst-portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeSanitaria.cls?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AnagrafeSanitaria(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AnagrafeSanitaria(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnagrafeSanitaria() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AnagrafeSanitaria(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AnagrafeSanitaria(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AnagrafeSanitaria(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AnagrafeSanitariaSoap
     */
    @WebEndpoint(name = "AnagrafeSanitariaSoap")
    public AnagrafeSanitariaSoap getAnagrafeSanitariaSoap() {
        return super.getPort(AnagrafeSanitariaSoap, AnagrafeSanitariaSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnagrafeSanitariaSoap
     */
    @WebEndpoint(name = "AnagrafeSanitariaSoap")
    public AnagrafeSanitariaSoap getAnagrafeSanitariaSoap(WebServiceFeature... features) {
        return super.getPort(AnagrafeSanitariaSoap, AnagrafeSanitariaSoap.class, features);
    }

}
