/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsanaura.stub.aura.auraws.services.central.contattodigitale;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-09-30T09:54:17.591+02:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "ContattoDigitale",
                  wsdlLocation = "file:/C:/Users/2132/Progetti/springwork/wsdl2java/src/main/resources/wsdl/ContattoDigitale.wsdl",
                  targetNamespace = "http://ContattoDigitale.central.services.auraws.aura.csi.it")
public class ContattoDigitale_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ContattoDigitale.central.services.auraws.aura.csi.it", "ContattoDigitale");
    public final static QName ContattoDigitaleSoap = new QName("http://ContattoDigitale.central.services.auraws.aura.csi.it", "ContattoDigitaleSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/2132/Progetti/springwork/wsdl2java/src/main/resources/wsdl/ContattoDigitale.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ContattoDigitale_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/2132/Progetti/springwork/wsdl2java/src/main/resources/wsdl/ContattoDigitale.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ContattoDigitale_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ContattoDigitale_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContattoDigitale_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ContattoDigitale_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ContattoDigitale_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ContattoDigitale_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ContattoDigitaleSoap
     */
    @WebEndpoint(name = "ContattoDigitaleSoap")
    public ContattoDigitaleSoap getContattoDigitaleSoap() {
        return super.getPort(ContattoDigitaleSoap, ContattoDigitaleSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContattoDigitaleSoap
     */
    @WebEndpoint(name = "ContattoDigitaleSoap")
    public ContattoDigitaleSoap getContattoDigitaleSoap(WebServiceFeature... features) {
        return super.getPort(ContattoDigitaleSoap, ContattoDigitaleSoap.class, features);
    }

}
