/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.dma.apiopsanaura.stub.aura.auraws.services.central.contattodigitale;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-09-30T09:54:17.490+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://ContattoDigitale.central.services.auraws.aura.csi.it", name = "ContattoDigitaleSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ContattoDigitaleSoap {

    @WebMethod(operationName = "ContattoDigitale", action = "http://ContattoDigitale.central.services.auraws.aura.csi.it/AURA.BS.ContattoDigitale.ContattoDigitale")
    @RequestWrapper(localName = "ContattoDigitale", targetNamespace = "http://ws.sanitxint.sanitx.csi.it/", className = "io.codejournal.maven.wsdl2java.ContattoDigitale")
    @ResponseWrapper(localName = "ContattoDigitaleResponse", targetNamespace = "http://ws.sanitxint.sanitx.csi.it/", className = "io.codejournal.maven.wsdl2java.ContattoDigitaleResponse")
    @WebResult(name = "return", targetNamespace = "http://ws.sanitxint.sanitx.csi.it/")
    public it.csi.dma.apiopsanaura.stub.aura.auraws.services.central.contattodigitale.ResponseContattoDigitale contattoDigitale(

        @WebParam(name = "pRequest", targetNamespace = "http://ws.sanitxint.sanitx.csi.it/")
        it.csi.dma.apiopsanaura.stub.aura.auraws.services.central.contattodigitale.RequestContattoDigitale pRequest
    );
}
