/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


package it.csi.aura.auraws.services.central.elencoesenzioni;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-14T11:57:54.770+02:00
 * Generated source version: 3.3.2
 *
 */
public final class ElencoEsenzioniSoap_ElencoEsenzioniSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://ElencoEsenzioni.central.services.auraws.aura.csi.it", "ElencoEsenzioni");

    private ElencoEsenzioniSoap_ElencoEsenzioniSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ElencoEsenzioni_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ElencoEsenzioni_Service ss = new ElencoEsenzioni_Service(wsdlURL, SERVICE_NAME);
        ElencoEsenzioniSoap port = ss.getElencoEsenzioniSoap();

        {
        System.out.println("Invoking elencoEsenzioni...");
        it.csi.aura.auraws.services.central.elencoesenzioni.RequestElencoEsenzioni _elencoEsenzioni_pRequest = null;
        it.csi.aura.auraws.services.central.elencoesenzioni.ResponseElencoEsenzioni _elencoEsenzioni__return = port.elencoEsenzioni(_elencoEsenzioni_pRequest);
        System.out.println("elencoEsenzioni.result=" + _elencoEsenzioni__return);


        }

        System.exit(0);
    }

}
