/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.aura.auraws.services.central.elencoesenzioni;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-14T11:57:54.834+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://ElencoEsenzioni.central.services.auraws.aura.csi.it", name = "ElencoEsenzioniSoap")
@XmlSeeAlso({it.csi.sanitx.sanitxint.ws.ObjectFactory.class, ObjectFactory.class})
public interface ElencoEsenzioniSoap {

    @WebMethod(operationName = "ElencoEsenzioni", action = "http://ElencoEsenzioni.central.services.auraws.aura.csi.it/AURA.BS.ElencoEsenzioni.ElencoEsenzioni")
    @RequestWrapper(localName = "ElencoEsenzioni", targetNamespace = "http://ElencoEsenzioni.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.elencoesenzioni.ElencoEsenzioni")
    @ResponseWrapper(localName = "ElencoEsenzioniResponse", targetNamespace = "http://ElencoEsenzioni.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.elencoesenzioni.ElencoEsenzioniResponse")
    @WebResult(name = "ElencoEsenzioniResult", targetNamespace = "http://ElencoEsenzioni.central.services.auraws.aura.csi.it")
    public it.csi.aura.auraws.services.central.elencoesenzioni.ResponseElencoEsenzioni elencoEsenzioni(

        @WebParam(name = "pRequest", targetNamespace = "http://ElencoEsenzioni.central.services.auraws.aura.csi.it")
        it.csi.aura.auraws.services.central.elencoesenzioni.RequestElencoEsenzioni pRequest
    );
}
