/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


package it.csi.aura.auraws.services.central.contattodigitale;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-14T11:58:11.860+02:00
 * Generated source version: 3.3.2
 *
 */
public final class ContattoDigitaleSoap_ContattoDigitaleSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://ContattoDigitale.central.services.auraws.aura.csi.it", "ContattoDigitale");

    private ContattoDigitaleSoap_ContattoDigitaleSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ContattoDigitale_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ContattoDigitale_Service ss = new ContattoDigitale_Service(wsdlURL, SERVICE_NAME);
        ContattoDigitaleSoap port = ss.getContattoDigitaleSoap();

        {
        System.out.println("Invoking contattoDigitale...");
        it.csi.aura.auraws.services.central.contattodigitale.RequestContattoDigitale _contattoDigitale_pRequest = null;
        it.csi.aura.auraws.services.central.contattodigitale.ResponseContattoDigitale _contattoDigitale__return = port.contattoDigitale(_contattoDigitale_pRequest);
        System.out.println("contattoDigitale.result=" + _contattoDigitale__return);


        }

        System.exit(0);
    }

}
