/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.aura.auraws.services.central.contattodigitale;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-14T11:58:11.957+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://ContattoDigitale.central.services.auraws.aura.csi.it", name = "ContattoDigitaleSoap")
@XmlSeeAlso({it.csi.sanitx.sanitxint.ws.ObjectFactory.class, ObjectFactory.class})
public interface ContattoDigitaleSoap {

    @WebMethod(operationName = "ContattoDigitale", action = "http://ContattoDigitale.central.services.auraws.aura.csi.it/AURA.BS.ContattoDigitale.ContattoDigitale")
    @RequestWrapper(localName = "ContattoDigitale", targetNamespace = "http://ContattoDigitale.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.contattodigitale.ContattoDigitale")
    @ResponseWrapper(localName = "ContattoDigitaleResponse", targetNamespace = "http://ContattoDigitale.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.contattodigitale.ContattoDigitaleResponse")
    @WebResult(name = "ContattoDigitaleResult", targetNamespace = "http://ContattoDigitale.central.services.auraws.aura.csi.it")
    public it.csi.aura.auraws.services.central.contattodigitale.ResponseContattoDigitale contattoDigitale(

        @WebParam(name = "pRequest", targetNamespace = "http://ContattoDigitale.central.services.auraws.aura.csi.it")
        it.csi.aura.auraws.services.central.contattodigitale.RequestContattoDigitale pRequest
    );
}
