/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.aura.auraws.services.central.anagrafefind;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-14T12:05:49.933+02:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "AnagrafeFind",
                  wsdlLocation = "https://tst-portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeFind.cls?wsdl",
                  targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it")
public class AnagrafeFind extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFind");
    public final static QName AnagrafeFindSoap = new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFindSoap");
    static {
        URL url = null;
        try {
            url = new URL("https://tst-portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeFind.cls?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AnagrafeFind.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "https://tst-portale.ruparpiemonte.it/sanitxens/AURA.WS.AnagrafeFind.cls?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AnagrafeFind(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AnagrafeFind(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnagrafeFind() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AnagrafeFind(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AnagrafeFind(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AnagrafeFind(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns AnagrafeFindSoap
     */
    @WebEndpoint(name = "AnagrafeFindSoap")
    public AnagrafeFindSoap getAnagrafeFindSoap() {
        return super.getPort(AnagrafeFindSoap, AnagrafeFindSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnagrafeFindSoap
     */
    @WebEndpoint(name = "AnagrafeFindSoap")
    public AnagrafeFindSoap getAnagrafeFindSoap(WebServiceFeature... features) {
        return super.getPort(AnagrafeFindSoap, AnagrafeFindSoap.class, features);
    }

}
