/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/


package it.csi.aura.auraws.services.central.anagrafefind;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-14T12:05:49.846+02:00
 * Generated source version: 3.3.2
 *
 */
public final class AnagrafeFindSoap_AnagrafeFindSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFind");

    private AnagrafeFindSoap_AnagrafeFindSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AnagrafeFind.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        AnagrafeFind ss = new AnagrafeFind(wsdlURL, SERVICE_NAME);
        AnagrafeFindSoap port = ss.getAnagrafeFindSoap();

        {
        System.out.println("Invoking findProfiliAnagrafici...");
        it.csi.aura.auraws.services.central.anagrafefind.FindProfiliAnagraficiRequest _findProfiliAnagrafici_profiliRequest = null;
        it.csi.aura.auraws.services.central.anagrafefind.DatiAnagraficiMsg _findProfiliAnagrafici__return = port.findProfiliAnagrafici(_findProfiliAnagrafici_profiliRequest);
        System.out.println("findProfiliAnagrafici.result=" + _findProfiliAnagrafici__return);


        }

        System.exit(0);
    }

}
