/*******************************************************************************
* Copyright Regione Piemonte - 2023
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.aura.auraws.services.central.anagrafefind;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2022-07-14T12:05:49.923+02:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it", name = "AnagrafeFindSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface AnagrafeFindSoap {

    @WebMethod(operationName = "FindProfiliAnagrafici", action = "http://AnagrafeFind.central.services.auraws.aura.csi.it/AURA.WS.AnagrafeFind.FindProfiliAnagrafici")
    @RequestWrapper(localName = "FindProfiliAnagrafici", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.anagrafefind.FindProfiliAnagrafici")
    @ResponseWrapper(localName = "FindProfiliAnagraficiResponse", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.anagrafefind.FindProfiliAnagraficiResponse")
    @WebResult(name = "FindProfiliAnagraficiResult", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it")
    public it.csi.aura.auraws.services.central.anagrafefind.DatiAnagraficiMsg findProfiliAnagrafici(

        @WebParam(name = "profiliRequest", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it")
        it.csi.aura.auraws.services.central.anagrafefind.FindProfiliAnagraficiRequest profiliRequest
    );
}
